### ISSUE TITLE
infinite recursion while testing pico language in util::TestIDE

### ISSUE THREAD

**Issue by jurgenvinju** [cwi-swat/rascal-vscode#32]
registering the language triggers the following `StackOverflow()`:

```
java.lang.StackOverflowError
	at io.usethesource.vallang.type.Type.intersectsWithExternal(Type.java:706)
	at io.usethesource.vallang.type.ExternalType.intersects(ExternalType.java:62)
	at io.usethesource.vallang.type.Type.intersectsWithExternal(Type.java:706)
	at io.usethesource.vallang.type.ExternalType.intersects(ExternalType.java:6
	...
```

**Comment by jurgenvinju** [comment]
solved by fixing two bugs in rascal
