### ISSUE TITLE
Do not try to read file contents from disk, always get the contents based on LSP state

### ISSUE THREAD

**Issue by DavyLandman** [cwi-swat/rascal-vscode#57]
If you open a new file, we can get these exceptions:

```

2021-07-13 10:10:31,968 [pool-2-thread-18] ERROR - org.rascalmpl.vscode.lsp.rascal.RascalTextDocumentService Error opening file |unknown:///| to get contents
org.rascalmpl.uri.UnsupportedSchemeException: Unsupported scheme unknown
	at org.rascalmpl.uri.URIResolverRegistry.getCharset(URIResolverRegistry.java:774) ~[rascal.jar:?]
	at org.rascalmpl.uri.URIResolverRegistry.getCharacterReader(URIResolverRegistry.java:716) ~[rascal.jar:?]
	at org.rascalmpl.vscode.lsp.rascal.RascalTextDocumentService.getContents(RascalTextDocumentService.java:123) ~[rascal-lsp.jar:?]
	at org.rascalmpl.vscode.lsp.util.locations.ColumnMaps.lambda$0(ColumnMaps.java:46) ~[rascal-lsp.jar:?]
	at com.github.benmanes.caffeine.cache.LocalLoadingCache.lambda$newMappingFunction$2(LocalLoadingCache.java:141) ~[rascal.jar:?]
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2346) ~[rascal.jar:?]
	at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1853) ~[?:1.8.0_292]
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2344) ~[rascal.jar:?]
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2327) ~[rascal.jar:?]
	at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:108) ~[rascal.jar:?]
	at com.github.benmanes.caffeine.cache.LocalLoadingCache.get(LocalLoadingCache.java:54) ~[rascal.jar:?]
	at org.rascalmpl.vscode.lsp.util.locations.ColumnMaps.get(ColumnMaps.java:50) ~[rascal-lsp.jar:?]
	at org.rascalmpl.vscode.lsp.util.locations.Locations.toRange(Locations.java:62) ~[rascal-lsp.jar:?]
	at org.rascalmpl.vscode.lsp.util.Diagnostics.translateDiagnostic(Diagnostics.java:89) ~[rascal-lsp.jar:?]
	at org.rascalmpl.vscode.lsp.util.Diagnostics.lambda$5(Diagnostics.java:109) ~[rascal-lsp.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_292]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_292]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_292]
	at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[?:1.8.0_292]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:1.8.0_292]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_292]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_292]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_292]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_292]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566) ~[?:1.8.0_292]
	at org.rascalmpl.vscode.lsp.util.Diagnostics.translateDiagnostics(Diagnostics.java:110) ~[rascal-lsp.jar:?]
	at org.rascalmpl.vscode.lsp.rascal.model.FileFacts$FileFact.lambda$6(FileFacts.java:155) ~[rascal-lsp.jar:?]
	at java.util.HashMap.forEach(HashMap.java:1289) ~[?:1.8.0_292]
	at org.rascalmpl.vscode.lsp.rascal.model.FileFacts$FileFact.lambda$5(FileFacts.java:155) ~[rascal-lsp.jar:?]
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:616) [?:1.8.0_292]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:591) [?:1.8.0_292]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_292]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1609) [?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
```

this points towards us opening files on disk instead of using the filestate of the LSP.

**Comment by DavyLandman** [comment]
This issue was fixed by a recent commit by droppig messages put on the "unknown" scheme. Rascal core should be changed to not generate them anymore.
