### ISSUE TITLE
deadlock at terminal start

### ISSUE THREAD

**Issue by jurgenvinju** [cwi-swat/rascal-vscode#64]
after adding the support for column fixes in the implementation of `util::IDEServices::applyEdits` (but it may also be an earlier edit), I get the following "deadlock":

```
"main" #1 prio=5 os_prio=31 tid=0x00007fda9f009000 nid=0x2903 waiting on condition [0x0000700002a68000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x000000076c717f10> (a java.util.concurrent.CompletableFuture$Signaller)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1707)
        at java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3323)
        at java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1742)
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1908)
        at org.rascalmpl.vscode.lsp.terminal.TerminalIDEClient.resolveProjectLocation(TerminalIDEClient.java:81)
        at org.rascalmpl.vscode.lsp.terminal.LSPTerminalREPL$1$$Lambda$40/1883840933.apply(Unknown Source)
        at org.rascalmpl.vscode.lsp.uri.TargetURIResolver.resolve(TargetURIResolver.java:49)
        at org.rascalmpl.uri.URIResolverRegistry.physicalLocation(URIResolverRegistry.java:283)
        at org.rascalmpl.uri.URIResolverRegistry.logicalToPhysical(URIResolverRegistry.java:256)
        at org.rascalmpl.uri.classloaders.SourceLocationClassLoader.initialize(SourceLocationClassLoader.java:54)
        at org.rascalmpl.uri.classloaders.SourceLocationClassLoader.<init>(SourceLocationClassLoader.java:41)
        at org.rascalmpl.vscode.lsp.terminal.LSPTerminalREPL$1.constructEvaluator(LSPTerminalREPL.java:115)
        at org.rascalmpl.repl.RascalInterpreterREPL.initialize(RascalInterpreterREPL.java:74)
        at org.rascalmpl.repl.BaseREPL.initialize(BaseREPL.java:159)
        at org.rascalmpl.repl.BaseREPL.<init>(BaseREPL.java:113)
        at org.rascalmpl.repl.BaseREPL.<init>(BaseREPL.java:62)
        at org.rascalmpl.vscode.lsp.terminal.LSPTerminalREPL.<init>(LSPTerminalREPL.java:80)
        at org.rascalmpl.vscode.lsp.terminal.LSPTerminalREPL.main(LSPTerminalREPL.java:231)
```

**Comment by jurgenvinju** [comment]
weird enough, no other references to the lock object in jstack output:

```
2021-08-23 17:06:26
Full thread dump OpenJDK 64-Bit Server VM (25.292-b10 mixed mode):

"Attach Listener" #20 daemon prio=9 os_prio=31 tid=0x00007fda9e124800 nid=0x5807 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Thread-4" #19 daemon prio=5 os_prio=31 tid=0x00007fda9f168800 nid=0x9f03 waiting on condition [0x00007000046ea000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x000000076bf429d0> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

"file:/// watcher thread-pool" #18 daemon prio=5 os_prio=31 tid=0x00007fdaa18ce000 nid=0x5f03 waiting on condition [0x00007000045e7000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x000000076bf41ad8> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.LinkedBlockingDeque.takeFirst(LinkedBlockingDeque.java:492)
	at java.util.concurrent.LinkedBlockingDeque.take(LinkedBlockingDeque.java:680)
	at sun.nio.fs.AbstractWatchService.take(AbstractWatchService.java:118)
	at org.rascalmpl.uri.file.FileURIResolver.lambda$createFileWatchingThread$2(FileURIResolver.java:292)
	at org.rascalmpl.uri.file.FileURIResolver$$Lambda$33/54495403.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

"NonBlockingInputStreamThread" #16 daemon prio=5 os_prio=31 tid=0x00007fdaa202c800 nid=0x5d03 in Object.wait() [0x00007000043e1000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x000000076bb82d38> (a jline.internal.NonBlockingInputStream)
	at jline.internal.NonBlockingInputStream.run(NonBlockingInputStream.java:275)
	- locked <0x000000076bb82d38> (a jline.internal.NonBlockingInputStream)
	at java.lang.Thread.run(Thread.java:748)

"InputStream scanner" #15 daemon prio=5 os_prio=31 tid=0x00007fda9e28f800 nid=0x5c03 runnable [0x00007000042de000]
   java.lang.Thread.State: RUNNABLE
	at java.io.FileInputStream.readBytes(Native Method)
	at java.io.FileInputStream.read(FileInputStream.java:255)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
	- locked <0x000000076ab1c500> (a java.io.BufferedInputStream)
	at org.rascalmpl.repl.NotifieableInputStream.lambda$new$0(NotifieableInputStream.java:30)
	at org.rascalmpl.repl.NotifieableInputStream$$Lambda$27/117244645.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:748)

"Cleanup Thread for io.usethesource.vallang.util.WeakWriteLockingHashConsingMap" #14 daemon prio=5 os_prio=31 tid=0x00007fdaa2875000 nid=0x5a03 waiting on condition [0x00007000041db000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
	at java.lang.Thread.sleep(Native Method)
	at io.usethesource.vallang.util.WeakWriteLockingHashConsingMap$CleanupThread.run(WeakWriteLockingHashConsingMap.java:211)

"pool-1-thread-1" #13 prio=5 os_prio=31 tid=0x00007fda9f159800 nid=0x5903 runnable [0x00007000040d8000]
   java.lang.Thread.State: RUNNABLE
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.net.SocketInputStream.read(SocketInputStream.java:224)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:79)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

"Service Thread" #9 daemon prio=9 os_prio=31 tid=0x00007fdaa1814000 nid=0xa703 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C1 CompilerThread3" #8 daemon prio=9 os_prio=31 tid=0x00007fda9f009800 nid=0xa903 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread2" #7 daemon prio=9 os_prio=31 tid=0x00007fdaa2008800 nid=0x3b03 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread1" #6 daemon prio=9 os_prio=31 tid=0x00007fdaa1809000 nid=0x3903 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread0" #5 daemon prio=9 os_prio=31 tid=0x00007fda9e045800 nid=0x3803 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Signal Dispatcher" #4 daemon prio=9 os_prio=31 tid=0x00007fda9e01b800 nid=0x3603 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Finalizer" #3 daemon prio=8 os_prio=31 tid=0x00007fda9d857000 nid=0x4403 in Object.wait() [0x000070000378f000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x000000076ab08ee0> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:144)
	- locked <0x000000076ab08ee0> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:165)
	at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:216)

"Reference Handler" #2 daemon prio=10 os_prio=31 tid=0x00007fda9d854000 nid=0x4503 in Object.wait() [0x000070000368c000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x000000076ab06c00> (a java.lang.ref.Reference$Lock)
	at java.lang.Object.wait(Object.java:502)
	at java.lang.ref.Reference.tryHandlePending(Reference.java:191)
	- locked <0x000000076ab06c00> (a java.lang.ref.Reference$Lock)
	at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:153)

"main" #1 prio=5 os_prio=31 tid=0x00007fda9f009000 nid=0x2903 waiting on condition [0x0000700002a68000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x000000076c717f10> (a java.util.concurrent.CompletableFuture$Signaller)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1707)
	at java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3323)
	at java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1742)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1908)
	at org.rascalmpl.vscode.lsp.terminal.TerminalIDEClient.resolveProjectLocation(TerminalIDEClient.java:81)
	at org.rascalmpl.vscode.lsp.terminal.LSPTerminalREPL$1$$Lambda$40/1883840933.apply(Unknown Source)
	at org.rascalmpl.vscode.lsp.uri.TargetURIResolver.resolve(TargetURIResolver.java:49)
	at org.rascalmpl.uri.URIResolverRegistry.physicalLocation(URIResolverRegistry.java:283)
	at org.rascalmpl.uri.URIResolverRegistry.logicalToPhysical(URIResolverRegistry.java:256)
	at org.rascalmpl.uri.classloaders.SourceLocationClassLoader.initialize(SourceLocationClassLoader.java:54)
	at org.rascalmpl.uri.classloaders.SourceLocationClassLoader.<init>(SourceLocationClassLoader.java:41)
	at org.rascalmpl.vscode.lsp.terminal.LSPTerminalREPL$1.constructEvaluator(LSPTerminalREPL.java:115)
	at org.rascalmpl.repl.RascalInterpreterREPL.initialize(RascalInterpreterREPL.java:74)
	at org.rascalmpl.repl.BaseREPL.initialize(BaseREPL.java:159)
	at org.rascalmpl.repl.BaseREPL.<init>(BaseREPL.java:113)
	at org.rascalmpl.repl.BaseREPL.<init>(BaseREPL.java:62)
	at org.rascalmpl.vscode.lsp.terminal.LSPTerminalREPL.<init>(LSPTerminalREPL.java:80)
	at org.rascalmpl.vscode.lsp.terminal.LSPTerminalREPL.main(LSPTerminalREPL.java:231)

"VM Thread" os_prio=31 tid=0x00007fda9d84d800 nid=0x4703 runnable 

"GC task thread#0 (ParallelGC)" os_prio=31 tid=0x00007fda9f015800 nid=0x1f07 runnable 

"GC task thread#1 (ParallelGC)" os_prio=31 tid=0x00007fda9d80d000 nid=0x1d03 runnable 

"GC task thread#2 (ParallelGC)" os_prio=31 tid=0x00007fda9f016000 nid=0x5403 runnable 

"GC task thread#3 (ParallelGC)" os_prio=31 tid=0x00007fda9e00f000 nid=0x2b03 runnable 

"GC task thread#4 (ParallelGC)" os_prio=31 tid=0x00007fda9e00f800 nid=0x2c03 runnable 

"GC task thread#5 (ParallelGC)" os_prio=31 tid=0x00007fda9e010800 nid=0x5003 runnable 

"GC task thread#6 (ParallelGC)" os_prio=31 tid=0x00007fda9e011000 nid=0x4e03 runnable 

"GC task thread#7 (ParallelGC)" os_prio=31 tid=0x00007fda9e012000 nid=0x4d03 runnable 

"GC task thread#8 (ParallelGC)" os_prio=31 tid=0x00007fda9e012800 nid=0x4b03 runnable 

"GC task thread#9 (ParallelGC)" os_prio=31 tid=0x00007fda9e013800 nid=0x4903 runnable 

"VM Periodic Task Thread" os_prio=31 tid=0x00007fdaa1815000 nid=0x5703 waiting on condition 

JNI global references: 448


```

**Comment by jurgenvinju** [comment]
maybe this is the offending commit: 40c955c7815fbbb4cd2a81acef6ecb993819f566

**Comment by DavyLandman** [comment]
the deadlock could be on the vs code side? that it's sending something, but we are still waiting to finish this before we start replying?

**Comment by DavyLandman** [comment]
I suspect you are calling something here: `org.rascalmpl.vscode.lsp.terminal.TerminalIDEClient.resolveProjectLocation(TerminalIDEClient.java:81)` that is not yet ready..

**Comment by DavyLandman** [comment]
so maybe the resolve should also be async? instead of explictally blocking there?

**Comment by jurgenvinju** [comment]
I'll rewrite the code to get the information pushed during init instead of asking for it just in time. This is how we solved it before in a different part.

**Comment by jurgenvinju** [comment]
Note to self: remove the whole notification from the interface to avoid future regressions
